version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: price_alert_db

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A price_alert_app worker -l info
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A price_alert_app beat -l info
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
